//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCArchitecture
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBL_EMPLOYEES
    {
        public int EMP_ID { get; set; }
        [Required]
        public string EMP_Name { get; set; }
        public Nullable<System.DateTime> EMP_DOB { get; set; }
        [Required]
        public Nullable<decimal> EMP_SALARY { get; set; }
        [Required]
        public Nullable<int> Manager_Id { get; set; }
        public Nullable<bool> IsTrainer { get; set; }
    }
}
