//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAdvance.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserLogin
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Please insert the username")]
        public string Username { get; set; }
       
        [Required(ErrorMessage = "Password required")]
        public string Password { get; set; }
        public string Role { get; set; }
    }
}
